In [3]:
import tensorflow as tf
import matplotlib.pyplot as plt
from sklearn.cross_validation import train_test_split
from sklearn import preprocessing
import pandas as pd
import numpy as np

df = pd.read_csv('air.csv')

y = df['scaled_sound'].as_matrix().reshape(-1,1)
x = df.drop('scaled_sound',axis=1).as_matrix()

X_s = preprocessing.scale(x)


In [4]:
print(X_s)

[[-0.6620227  -1.14640293  1.79929926  1.31293526 -0.64480461]
 [-0.59856135 -1.14640293  1.79929926  1.31293526 -0.64480461]
 [-0.51923465 -1.14640293  1.79929926  1.31293526 -0.64480461]
 ..., 
 [ 0.353359    1.49044302 -0.37373954 -0.72334483  3.17277251]
 [ 0.67066578  1.49044302 -0.37373954 -0.72334483  3.17277251]
 [ 1.08316459  1.49044302 -0.37373954 -0.72334483  3.17277251]]


In [6]:
X_n = x
X_n /= np.std(x, axis=0)
X_n -= np.mean(x, axis=0)
print(X_n)

[[-0.6620227  -1.14640293  1.79929926  1.31293526 -0.64480461]
 [-0.59856135 -1.14640293  1.79929926  1.31293526 -0.64480461]
 [-0.51923465 -1.14640293  1.79929926  1.31293526 -0.64480461]
 ..., 
 [ 0.353359    1.49044302 -0.37373954 -0.72334483  3.17277251]
 [ 0.67066578  1.49044302 -0.37373954 -0.72334483  3.17277251]
 [ 1.08316459  1.49044302 -0.37373954 -0.72334483  3.17277251]]


In [7]:
df.describe()

freq        angle  chord_length  free_stream_velocity  \
count   1503.000000  1503.000000   1503.000000           1503.000000   
mean    2886.380572     6.782302      0.136548             50.860745   
std     3152.573137     5.918128      0.093541             15.572784   
min      200.000000     0.000000      0.025400             31.700000   
25%      800.000000     2.000000      0.050800             39.600000   
50%     1600.000000     5.400000      0.101600             39.600000   
75%     4000.000000     9.900000      0.228600             71.300000   
max    20000.000000    22.200000      0.304800             71.300000   

       displacement_thickness  scaled_sound  
count             1503.000000   1503.000000  
mean                 0.011140    124.835943  
std                  0.013150      6.898657  
min                  0.000401    103.380000  
25%                  0.002535    120.191000  
50%                  0.004957    125.721000  
75%                  0.015576    129.995500  
max                  0.058411    140.987000

In [8]:
df.head()

freq  angle  chord_length  free_stream_velocity  displacement_thickness  \
0   800    0.0        0.3048                  71.3                0.002663   
1  1000    0.0        0.3048                  71.3                0.002663   
2  1250    0.0        0.3048                  71.3                0.002663   
3  1600    0.0        0.3048                  71.3                0.002663   
4  2000    0.0        0.3048                  71.3                0.002663   

   scaled_sound  
0       126.201  
1       125.201  
2       125.951  
3       127.591  
4       127.461